const profils = {
    "data": {
        "id": 10,
        "name": "Adi Abd Fahram",
        "first_name": "Adi Abd",
        "last_name": "Fahram",
        "business_name": null,
        "email": "jemovegoxy@mailinator.com",
        "email_verified_at": null,
        "two_factor_secret": null,
        "two_factor_recovery_codes": null,
        "address": null,
        "address2": null,
        "phone": "01242366345",
        "birthday": null,
        "city": null,
        "state": null,
        "country": "ID",
        "zip_code": null,
        "last_login_at": null,
        "avatar_id": null,
        "bio": null,
        "status": "publish",
        "create_user": null,
        "update_user": null,
        "vendor_commission_amount": null,
        "vendor_commission_type": null,
        "need_update_pw": 0,
        "role_id": 3,
        "deleted_at": null,
        "created_at": "2024-04-04T22:04:42.000000Z",
        "updated_at": "2024-04-05T04:01:02.000000Z",
        "payment_gateway": null,
        "total_guests": null,
        "locale": null,
        "user_name": null,
        "verify_submit_status": null,
        "is_verified": null,
        "active_status": 0,
        "dark_mode": 0,
        "messenger_color": "#2180f3",
        "stripe_customer_id": null,
        "total_before_fees": null
    },
    "status": 1
};

export default profils;